spring:
  application:
    name: book-sphere
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    password: password
    username: postgres
server:
  port: 8080
