spring:
  application:
    name: book-sphere
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    password: password
    username: postgres
  web:
    locale: en
    locale-resolver: fixed

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000